In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.4.0


In [2]:
sess = tf.Session()

In [3]:
# 기본적으로 concat는 tensor를 붙이는데 사용한다.
x1 = np.array([[1,2]])
x2 = np.array([[3,4]])

y1 = tf.concat([x1,x2],0)
y2 = tf.concat([x1,x2],1)

print('axis=0에서의 concat결과 : \n',sess.run(y1))
print('axis=1에서의 concat결과 : \n',sess.run(y2))


print('shape of x1 : ',x1.shape)
print('shape of x2 : ',x2.shape)
print('shape of y1 : ',y1.shape)
print('shape of y2 : ',y2.shape)

axis=0에서의 concat결과 : 
 [[1 2]
 [3 4]]
axis=1에서의 concat결과 : 
 [[1 2 3 4]]
shape of x1 :  (1, 2)
shape of x2 :  (1, 2)
shape of y1 :  (2, 2)
shape of y2 :  (1, 4)


다차원 concat

In [4]:
x = tf.constant([1,0,0,0,0,0,0,0,0,0], dtype = tf.float32)
x = tf.reshape(x,[1,1,1,10])

print('shape of x : ',x.shape)
print('x : \n',sess.run(x))

shape of x :  (1, 1, 1, 10)
x : 
 [[[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]]]


x*tf.ones([1,2,2,1], dtype = tf.float32) 이 연산에서 데이터 타입이 같아야한다.

In [5]:
y = x*tf.ones([1,2,2,1], dtype = tf.float32) 
print('shape of y : ',y.shape)
print('y : \n',sess.run(y))

shape of y :  (1, 2, 2, 10)
y : 
 [[[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
   [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

  [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
   [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]]]


[1,2,2,100]의 shape를 가진 z와 y의 concat

In [6]:
z = tf.ones([1,2,2,1], dtype = tf.float32)

Z = tf.concat([z,y],3)
print(Z.shape)
print('Z : \n', sess.run(Z))

(1, 2, 2, 11)
Z : 
 [[[[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
   [ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

  [[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
   [ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]]]
