In [1]:
import tensorflow as tf

print(tf.__version__)

1.4.0


# tf.reverse(tensor,axis, name=None)
주어진 tensor를 axis에 따라 반전시킨다<br/>
axis는 [0,1,2] or [True, False]와 같은 값을 가지며 해당 tensor의 차원을 반전시킨다<br/>

In [2]:
sess = tf.Session()

In [3]:
x1 = [1,2,3,4]

reverse1 = tf.reverse(x1,axis=[0])
print(sess.run(reverse1))

[4 3 2 1]


In [4]:
x2 = [[1,2,3,4],[5,6,7,8]]

reverse2 = tf.reverse(x2,axis=[0])
print(sess.run(reverse2))

reverse2 = tf.reverse(x2,axis=[1])
print(sess.run(reverse2))

reverse2 = tf.reverse(x2,axis=[0,1])
print(sess.run(reverse2))

[[5 6 7 8]
 [1 2 3 4]]
[[4 3 2 1]
 [8 7 6 5]]
[[8 7 6 5]
 [4 3 2 1]]


In [5]:
x2 = [[[1,2,3,4],[5,6,7,8]]]

reverse2 = tf.reverse(x2,axis=[0])
print(sess.run(reverse2))

reverse2 = tf.reverse(x2,axis=[1])
print(sess.run(reverse2))

reverse2 = tf.reverse(x2,axis=[2])
print(sess.run(reverse2))

reverse2 = tf.reverse(x2,axis=[1,2])
print(sess.run(reverse2))

[[[1 2 3 4]
  [5 6 7 8]]]
[[[5 6 7 8]
  [1 2 3 4]]]
[[[4 3 2 1]
  [8 7 6 5]]]
[[[8 7 6 5]
  [4 3 2 1]]]
