In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
x = torch.ones((4,4))
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Pytorch 입력의 형태
* input type: torch.Tensor
* input shape : `(batch_size, channel, height, width)`

In [3]:
x = x.view(-1, 1, 4, 4)
x

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [4]:
x.shape

torch.Size([1, 1, 4, 4])

## Conv2d

In [5]:
out = nn.Conv2d(1, 1, kernel_size = 3, stride = 1, padding = 1, bias = False)

In [6]:
nn.init.constant_(out.weight.data, 1) # initialize weights

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

### Convolution output size

$$ Output\;Size = floor(\frac{Input\;Size - Kernel\;Size + (2*padding)}{Stride})+1 $$

input size= 4, filter size= 3, padding= 1, Stride= 1

In [7]:
out(x)

tensor([[[[4., 6., 6., 4.],
          [6., 9., 9., 6.],
          [6., 9., 9., 6.],
          [4., 6., 6., 4.]]]], grad_fn=<ThnnConv2DBackward>)

In [8]:
out(x).shape

torch.Size([1, 1, 4, 4])

input size= 4, filter size= 3, padding= 2, Stride= 1

In [9]:
out.kernel_size = 3
out.padding = 2

In [10]:
out(x)

tensor([[[[1., 2., 3., 3., 2., 1.],
          [2., 4., 6., 6., 4., 2.],
          [3., 6., 9., 9., 6., 3.],
          [3., 6., 9., 9., 6., 3.],
          [2., 4., 6., 6., 4., 2.],
          [1., 2., 3., 3., 2., 1.]]]], grad_fn=<ThnnConv2DBackward>)

In [11]:
out(x).shape

torch.Size([1, 1, 6, 6])

## ConvTranspose2d
- Refer to https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html

`padding` controls the amount of implicit zero-paddings on both sides for `dilation * (kernel_size - 1) - padding` number of points. See note below for details.

위에서의 `padding`은 Transpose Conv를 위해 input에 추가로 들어가는 padding 수를 의미. <br>
따라서 아래 nn.ConvTranspose2d와 같이 padding = 0로 정할 경우, <br>
padding = 1*(3-1)-0 = 2. Input Size(4X4->6X6)

결국 ConvTrnspose2d 또한 <br>
padding을 붙이는 방식만 위와 같이 한 Conv2d 계산을 함(dilation=1일 때) 

## Padding Check

In [12]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, padding=0, output_padding=0, bias=False)
nn.init.constant_(transpose.weight.data,1)

tensor([[[[1., 1.],
          [1., 1.]]]])

In [13]:
nn.ZeroPad2d((1, 1, 1, 1))(x)

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 0., 0., 0., 0., 0.]]]])

In [14]:
transpose(x)

tensor([[[[1., 2., 2., 2., 1.],
          [2., 4., 4., 4., 2.],
          [2., 4., 4., 4., 2.],
          [2., 4., 4., 4., 2.],
          [1., 2., 2., 2., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

In [15]:
transpose(x).shape

torch.Size([1, 1, 5, 5])

In [16]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=2, stride=1, padding=1, output_padding=0, bias=False)
nn.init.constant_(transpose.weight.data,1)

tensor([[[[1., 1.],
          [1., 1.]]]])

In [17]:
nn.ZeroPad2d((0, 0, 0, 0))(x)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [18]:
transpose(x)

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

In [19]:
transpose(x).shape

torch.Size([1, 1, 3, 3])

refer to https://medium.com/apache-mxnet/transposed-convolutions-explained-with-ms-excel-52d13030c7e8
    - <Figure 9>참고

In [20]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, output_padding=0, bias=False)
nn.init.constant_(transpose.weight.data,1)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [21]:
nn.ZeroPad2d((2, 2, 2, 2))(x)

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 1., 1., 1., 1., 0., 0.],
          [0., 0., 1., 1., 1., 1., 0., 0.],
          [0., 0., 1., 1., 1., 1., 0., 0.],
          [0., 0., 1., 1., 1., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]])

input size= 4, filter size= 3, padding= 0, Stride= 1, output_padding = 0

In [22]:
transpose(x)

tensor([[[[1., 2., 3., 3., 2., 1.],
          [2., 4., 6., 6., 4., 2.],
          [3., 6., 9., 9., 6., 3.],
          [3., 6., 9., 9., 6., 3.],
          [2., 4., 6., 6., 4., 2.],
          [1., 2., 3., 3., 2., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

In [23]:
transpose(x).shape

torch.Size([1, 1, 6, 6])

input size= 4, filter size= 3, padding= 2(padding is zero), Stride= 1, output_padding = 0

In [24]:
nn.ZeroPad2d((0, 0, 0, 0))(x)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [25]:
transpose.output_padding = 0
transpose.padding = 2
transpose.stride = 1
transpose(x)

tensor([[[[9., 9.],
          [9., 9.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

In [26]:
transpose(x).shape

torch.Size([1, 1, 2, 2])

input size= 4, filter size= 3, padding= 0, Stride= 2, output_padding = 0

In [27]:
nn.ZeroPad2d((1, 1, 1, 1))(x)

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 1., 1., 1., 1., 0.],
          [0., 0., 0., 0., 0., 0.]]]])

In [28]:
transpose.output_padding = 0
transpose.padding = 2
transpose.stride = 2
transpose(x)

tensor([[[[4., 2., 4., 2., 4.],
          [2., 1., 2., 1., 2.],
          [4., 2., 4., 2., 4.],
          [2., 1., 2., 1., 2.],
          [4., 2., 4., 2., 4.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

In [29]:
transpose(x).shape

torch.Size([1, 1, 5, 5])

## Transpose Prac

In [77]:
tx = torch.ones((1,2,1,1))
tx

tensor([[[[1.]],

         [[1.]]]])

In [78]:
tx.shape

torch.Size([1, 2, 1, 1])

In [89]:
deconv1 = F.interpolate(F.leaky_relu(tx), scale_factor=2)
deconv1.shape

torch.Size([1, 2, 2, 2])

In [90]:
deconv1 = nn.ConvTranspose2d(2, 4, 7, bias=False, padding=0)(deconv1)
deconv1.shape

torch.Size([1, 4, 8, 8])