In [1]:
import numpy as np

# np.argsort(a, axis = -1, kind = 'quicksort', order = None)

In [2]:
x = np.array([1,3,2,4])
argsort_x = np.argsort(x)
print(argsort_x)

[0 2 1 3]


argsort의 결과물은 index인데 이 index는 오름 차순인 index 결과가 나온다.

위에서의 결과 [0 2 1 3]은 바로 x[0],x[2],x[1],x[3] 이며 순서대로 [1 2 3 4]이다.

밑에 sort의 결과와 함께보면 이해가 더 쉽게 된다.

In [3]:
print(np.sort(x))
print(x[argsort_x])

[1 2 3 4]
[1 2 3 4]
