In [1]:
import numpy as np

# np.argsort(a, axis = -1, kind = 'quicksort', order = None)

In [2]:
x = np.array([1,3,2,4])
argsort_x = np.argsort(x)
print(argsort_x)

[0 2 1 3]


argsort의 결과물은 index인데 이 index는 오름 차순인 index 결과가 나온다.

위에서의 결과 [0 2 1 3]은 바로 x[0],x[2],x[1],x[3] 이며 순서대로 [1 2 3 4]이다.

밑에 sort의 결과와 함께보면 이해가 더 쉽게 된다.

In [3]:
print(np.sort(x))
print(x[argsort_x])

[1 2 3 4]
[1 2 3 4]


# 1차원 이상 데이터 행렬일 경우
axis에 따른 결과 출력 

axis = 0일 경우, first axis에 따라 출력
axis = 1일 경우, last axis에 따라 출력

In [4]:
z = np.array([
    [0,1,3],
    [1,3,2],
    [2,0,4]
    ])
argsort_z1 = np.argsort(z, axis=0)
argsort_z2 = np.argsort(z, axis=1)

axis = 0일 경우

argsort_z1의 첫행의 [0 2 1]의 결과는
각각 z[:,0], z[:,1], z[:,2]에 대한 순번 결과이다.

axis = 1일 경우

argsort_z2의 첫행의 [0 1 2]의 결과는
각각 z[0,:]에 대한 순번 결과이다.


In [5]:
print('z : \n',z)
print('axis = 0 결과 : \n',argsort_z1)
print('axis = 1 결과 : \n',argsort_z2)

z : 
 [[0 1 3]
 [1 3 2]
 [2 0 4]]
axis = 0 결과 : 
 [[0 2 1]
 [1 0 0]
 [2 1 2]]
axis = 1 결과 : 
 [[0 1 2]
 [0 2 1]
 [1 0 2]]
