In [1]:
import numpy as np

# np.concatenate((a1, a2, ...), axis = 0, out = None)
axis에 따라 행렬을 합친다

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [4]:
ab0 = np.concatenate((a,b), axis = 0)
ab0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
ab1 = np.concatenate((a,b), axis = 1)
ab1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# np.vstack
np.concatenate에서 axis = 0와 같음

In [6]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# np.hstack
np.concatenate에서 axis = 1와 같음

In [7]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])